version: '3.8'

services:
  auth-service-app:
    build:
      context: ./AuthServiceApplication
      dockerfile: Dockerfile
    container_name: asp
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped
