spring:
  application:
    name: AuthServiceApplication
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true

resilience4j:
  ratelimiter:
    instances:
      myRateLimiter:
        limit-for-period: 5          # Allow 5 requests
        limit-refresh-period: 10s    # Time window: 10 seconds
        timeout-duration: 1s